package dataclass

import scala.annotation.StaticAnnotation

/** Scala 3 stand-in for the data-class `@data` macro annotation, for sources shared with Scala 2.
  *
  * A no-op: the annotated classes are plain case classes, and their binary-compatible `apply` /
  * `copy` / constructor overloads are generated by the unroll compiler plugin from the `@since`
  * annotations (see [[since]]).
  *
  * The parameters are those of the Scala 2 macro annotation, so that sources can pass them.
  * `cachedHashCode` and `settersCallApply` are implemented by the unroll plugin
  * (`DataClassPhaseScala3`, the latter for `copy` and `fromProduct`). `apply = false` needs
  * nothing: a companion `apply` with the constructor's signature already replaces the synthetic
  * one. The others only concern the setters the Scala 2 macro generates.
  */
class data(
  apply: Boolean = true,
  publicConstructor: Boolean = true,
  optionSetters: Boolean = false,
  settersCallApply: Boolean = false,
  cachedHashCode: Boolean = false
) extends StaticAnnotation
