#!/usr/bin/env bash
#
# Selective test execution on CI, on top of Mill's `selective.prepare` / `selective.run`.
#
# Mill snapshots the inputs of the requested tasks (sources, `Task.Input` values, and the code
# signature of the build methods) at the base commit of a pull request, and only runs the tests
# that transitively depend on something that changed since then. Tests that don't exist at the
# base commit count as changed.
#
# Usage:
#   selective-tests.sh prepare <selector>...    (empty selectors are ignored)
#   selective-tests.sh run [Mill option]... <selector>
#
# Selectors are Mill task selectors of test tasks, like `__:CsScalaJsTests.testForked` (see the
# `*CiTests` traits in mill-build). They must list the test tasks themselves: a command
# depending on several test tasks would be re-run, along with all of these tests, as soon as a
# single one of them is affected by a change.
#
# `prepare` must run once per job, before any `run`. It checks out the base commit of the pull
# request, snapshots the inputs of the tests of all the selectors, and checks out the pull request
# again. When selective execution can't be used - the build isn't a pull request build, the pull
# request changes the Mill version, or the selectors can't be resolved at the base commit - `run`
# runs all the tests of its selector.
#
# Environment:
#   SELECTIVE_TESTS_BASE_SHA  base commit of the pull request (empty or unset otherwise)
#   GITHUB_EVENT_NAME         set by GitHub Actions, selective execution is used for pull_request only
#   SCALA_VERSION, CI, …      read by build.mill, must be the same for `prepare` and `run`

set -euo pipefail

if [[ "$OSTYPE" == msys* || "$OSTYPE" == mingw* || "$OSTYPE" == cygwin* ]]; then
  MILL=./mill.bat
else
  MILL=./mill
fi

# Makes the build use a commit-independent version, so that the version baked into the sources
# generated by the build doesn't invalidate every test on every commit.
# See CoursierPublishModule.fixedVersionEnvVar in mill-build.
export COURSIER_SELECTIVE_TESTING=true

out_dir="${MILL_OUTPUT_DIR:-out}"
# written by selective.prepare, read by selective.run
snapshot="$out_dir/mill-selective-execution.json"
# our own copy of it, so that several `run`s can follow a single `prepare`
saved_snapshot="$out_dir/ci-selective-execution.json"

# Joins selectors into a single `{a,b,c}` one: the `selective.*` commands only take
# their first positional argument into account, extra ones are silently dropped.
# Empty selectors are ignored, and a single selector is left as is (`{a}` isn't expanded).
brace_selector() {
  local selectors=()
  local selector
  for selector in "$@"; do
    if [ -n "$selector" ]; then
      selectors+=("$selector")
    fi
  done
  if [ "${#selectors[@]}" -eq 0 ]; then
    echo ""
  elif [ "${#selectors[@]}" -eq 1 ]; then
    echo "${selectors[0]}"
  else
    local IFS=","
    echo "{${selectors[*]}}"
  fi
}

prepare() {
  rm -f "$saved_snapshot"

  local selector
  selector="$(brace_selector "$@")"
  if [ -z "$selector" ]; then
    echo "No tests to snapshot"
    return
  fi

  local base="${SELECTIVE_TESTS_BASE_SHA:-}"
  if [ "${GITHUB_EVENT_NAME:-}" != "pull_request" ] || [ -z "$base" ]; then
    echo "Not a pull request build, all tests will run"
    return
  fi

  local head
  head="$(git rev-parse HEAD)"

  # no `| head -n 1`: under `pipefail`, `git show` would be killed by SIGPIPE once head exits
  local base_build_mill head_build_mill base_mill_version head_mill_version
  base_build_mill="$(git show "$base:build.mill")"
  head_build_mill="$(cat build.mill)"
  base_mill_version="${base_build_mill%%$'\n'*}"
  head_mill_version="${head_build_mill%%$'\n'*}"
  if [ "$base_mill_version" != "$head_mill_version" ]; then
    echo "Mill version differs between the base commit and the pull request, all tests will run"
    return
  fi

  echo "Snapshotting the inputs of the tests at base commit $base"
  if ! git checkout --quiet "$base"; then
    echo "Could not check out base commit $base, all tests will run"
    return
  fi
  git submodule update --init --quiet

  local ok=true
  # fails if a selector can't be resolved at the base commit, like when it relies on a trait
  # the pull request adds
  if ! "$MILL" -i selective.prepare "$selector"; then
    ok=false
  fi

  git checkout --quiet "$head"
  git submodule update --init --quiet

  if $ok && [ -f "$snapshot" ]; then
    cp "$snapshot" "$saved_snapshot"
    echo "Selective execution enabled: only the tests affected by changes since $base will run"
  else
    echo "Could not snapshot the inputs of the tests at base commit $base, all tests will run"
  fi
}

run() {
  if [ "$#" -eq 0 ]; then
    echo "Usage: $0 run [Mill option]... <selector>" >&2
    exit 1
  fi
  local selector="${!#}"
  local mill_opts=("${@:1:$#-1}")
  # `${a[@]+"${a[@]}"}`: with `set -u`, bash < 4.4 (macOS) rejects "${a[@]}" for an empty array

  if [ ! -f "$saved_snapshot" ]; then
    echo "Running all tests"
    "$MILL" -i ${mill_opts[@]+"${mill_opts[@]}"} "$selector"
    return
  fi

  cp "$saved_snapshot" "$snapshot"
  echo "Inputs that changed since the base commit:"
  "$MILL" -i --ticker false selective.resolveChanged "$selector" || true
  echo "Tests affected by those changes:"
  "$MILL" -i --ticker false selective.resolve "$selector"
  "$MILL" -i ${mill_opts[@]+"${mill_opts[@]}"} selective.run "$selector"
}

case "${1:-}" in
  prepare)
    shift
    if [ "$#" -eq 0 ]; then
      echo "Usage: $0 prepare <selector>..." >&2
      exit 1
    fi
    prepare "$@"
    ;;
  run)
    shift
    run "$@"
    ;;
  *)
    echo "Usage: $0 prepare <selector>... | run [Mill option]... <selector>" >&2
    exit 1
    ;;
esac
