#!/usr/bin/env bash
#
# Selective test execution on CI, on top of Mill's `selective.prepare` / `selective.run`.
#
# Mill snapshots the inputs of the requested tasks (sources, `Task.Input` values, and the code
# signature of the build methods) at the base commit of a pull request, and only runs the tests
# that transitively depend on something that changed since then.
#
# Usage:
#   selective-tests.sh prepare <selectors command>...
#   selective-tests.sh run <selectors command> -- <Mill command running all the tests> [args]...
#
# `prepare` must run once per job, before any `run`. It checks out the base commit of the pull
# request, snapshots the inputs of the tests listed by the selectors commands, and checks out the
# pull request again. When selective execution can't be used - the build isn't a pull request
# build, the pull request changes the Mill version, or the base commit doesn't have the selectors
# commands - `run` falls back to the command given after `--`, and all the tests run.
#
# Selectors commands are the `ci.*TestSelectors` commands of build.mill: they print the tasks that
# the corresponding `*Tests` command runs, so that the tests can be handed to `selective.run` one by
# one. Passing the `*Tests` command itself to `selective.run` would re-run every test as soon as
# a single one is affected by a change.
#
# Environment:
#   SELECTIVE_TESTS_BASE_SHA  base commit of the pull request (empty or unset otherwise)
#   GITHUB_EVENT_NAME         set by GitHub Actions, selective execution is used for pull_request only
#   SCALA_VERSION, CI, …      read by build.mill, must be the same for `prepare` and `run`

set -euo pipefail

if [[ "$OSTYPE" == msys* || "$OSTYPE" == mingw* || "$OSTYPE" == cygwin* ]]; then
  MILL=./mill.bat
else
  MILL=./mill
fi

# Makes the build use a commit-independent version, so that the version baked into the sources
# generated by the build doesn't invalidate every test on every commit.
# See CoursierPublishModule.fixedVersionEnvVar in mill-build.
export COURSIER_SELECTIVE_TESTING=true

out_dir="${MILL_OUTPUT_DIR:-out}"
# written by selective.prepare, read by selective.run
snapshot="$out_dir/mill-selective-execution.json"
# our own copy of it, so that several `run`s can follow a single `prepare`
saved_snapshot="$out_dir/ci-selective-execution.json"

# Prints the tasks under the given key ("prerequisites" or "tests") of a selectors command
selectors() {
  local cmd="$1"
  local key="$2"
  "$MILL" -i --ticker false show "$cmd" | jq -r ".${key}[]"
}

read_lines_into() {
  local -n arr="$1"
  arr=()
  while IFS= read -r line; do
    if [ -n "$line" ]; then
      arr+=("$line")
    fi
  done
}

# Joins tasks into a single `{a,b,c}` selector: the `selective.*` commands only take
# their first positional argument into account, extra ones are silently dropped.
brace_selector() {
  local IFS=","
  echo "{$*}"
}

prepare() {
  rm -f "$saved_snapshot"

  local base="${SELECTIVE_TESTS_BASE_SHA:-}"
  if [ "${GITHUB_EVENT_NAME:-}" != "pull_request" ] || [ -z "$base" ]; then
    echo "Not a pull request build, all tests will run"
    return
  fi

  local head
  head="$(git rev-parse HEAD)"

  # no `| head -n 1`: under `pipefail`, `git show` would be killed by SIGPIPE once head exits
  local base_build_mill head_build_mill base_mill_version head_mill_version
  base_build_mill="$(git show "$base:build.mill")"
  head_build_mill="$(cat build.mill)"
  base_mill_version="${base_build_mill%%$'\n'*}"
  head_mill_version="${head_build_mill%%$'\n'*}"
  if [ "$base_mill_version" != "$head_mill_version" ]; then
    echo "Mill version differs between the base commit and the pull request, all tests will run"
    return
  fi

  echo "Snapshotting the inputs of the tests at base commit $base"
  if ! git checkout --quiet "$base"; then
    echo "Could not check out base commit $base, all tests will run"
    return
  fi
  git submodule update --init --quiet

  local ok=true
  local tasks=()
  local cmd_tasks=()
  local list
  for cmd in "$@"; do
    if list="$(selectors "$cmd" tests)"; then
      read_lines_into cmd_tasks <<< "$list"
      tasks+=("${cmd_tasks[@]}")
    else
      # the base commit doesn't have the selectors command, most likely
      ok=false
      break
    fi
  done

  if $ok && [ "${#tasks[@]}" -gt 0 ]; then
    if ! "$MILL" -i selective.prepare "$(brace_selector "${tasks[@]}")"; then
      ok=false
    fi
  fi

  git checkout --quiet "$head"
  git submodule update --init --quiet

  if $ok && [ -f "$snapshot" ]; then
    cp "$snapshot" "$saved_snapshot"
    echo "Selective execution enabled: only the tests affected by changes since $base will run"
  else
    echo "Could not snapshot the inputs of the tests at base commit $base, all tests will run"
  fi
}

run() {
  local cmd="$1"
  shift
  if [ "${1:-}" != "--" ]; then
    echo "Usage: $0 run <selectors command> -- <Mill command running all the tests> [args]..." >&2
    exit 1
  fi
  shift
  local fallback=("$@")

  if [ ! -f "$saved_snapshot" ]; then
    echo "Running all tests"
    "$MILL" -i "${fallback[@]}"
    return
  fi

  # `set -e` makes a failure of the selectors command fatal here
  local list
  local prerequisites=()
  list="$(selectors "$cmd" prerequisites)"
  read_lines_into prerequisites <<< "$list"
  for task in "${prerequisites[@]}"; do
    "$MILL" -i "$task"
  done

  local tests=()
  list="$(selectors "$cmd" tests)"
  read_lines_into tests <<< "$list"
  if [ "${#tests[@]}" -eq 0 ]; then
    echo "No tests to run"
    return
  fi

  local selector
  selector="$(brace_selector "${tests[@]}")"

  cp "$saved_snapshot" "$snapshot"
  echo "Inputs that changed since the base commit:"
  "$MILL" -i --ticker false selective.resolveChanged "$selector" || true
  echo "Tests affected by those changes:"
  "$MILL" -i --ticker false selective.resolve "$selector"
  "$MILL" -i selective.run "$selector"
}

case "${1:-}" in
  prepare)
    shift
    prepare "$@"
    ;;
  run)
    shift
    run "$@"
    ;;
  *)
    echo "Usage: $0 prepare <selectors command>... | run <selectors command> -- <Mill command> [args]..." >&2
    exit 1
    ;;
esac
