updates.ignore = [ { groupId = "org.scalaz", artifactId = "scalaz-core" } ]

# tika 3.x is compiled for Java 11, and we still support Java 8
updates.pin = [ { groupId = "org.apache.tika", artifactId = "tika-core", version = "2." } ]
