scala_library(
    name = "publish",
    dependencies = [
        "3rdparty/jvm:argonaut-shapeless",
        "3rdparty/jvm:okhttp",
        "3rdparty/jvm:emoji",
        "cache:cache",
        "core:core",
    ],
    sources = rglobs("src/main/*.scala"),
)
