scala_library(
    name = "util",
    dependencies = [
        "3rdparty/jvm:data-class",
        "3rdparty/jvm:jsoup",
    ],
    sources = rglobs("jvm/src/main/*.scala", "shared/src/main/*.scala"),
)
