scala_library(
  name = 'core',
  sources = rglobs('*.scala'),
  dependencies = [
    '3rdparty/jvm:fastParse',
    '3rdparty/jvm:scalaz-core',
    '3rdparty/jvm:jsoup',
    'core/shared/src/main/scala:shared'
   ]
)
