scala_library(
    name = "cache",
    dependencies = [
        "3rdparty/jvm:data-class",
        "3rdparty/jvm:jline-terminal-jansi",
        "3rdparty/jvm:jansi",
        "core:core",
        "paths/src/main/java:paths",
    ],
    sources = rglobs("jvm/src/main/*.scala", "shared/*.scala"),
)
