scala_library(
    name = "install",
    dependencies = [
        "3rdparty/jvm:argonaut-shapeless",
        "3rdparty/jvm:cats-core",
        "bootstrap:bootstrap",
        "coursier:coursier",
    ],
    sources = rglobs(
        "src/main/scala/*.scala",
    ),
)
