junit_tests(
    name = 'test',
    dependencies = [
       	"3rdparty/jvm:scalatest",
        "cli/src/main/scala-2.11:cli",
        "paths/src/main/java:paths",
    ],
    sources = globs("*.scala"),
)
