name: Test native launchers
on:
  push:
    branches:
    - master

jobs:

  test-native-launchers:
    strategy:
      fail-fast: false
      matrix:
        OS: [ubuntu-latest, windows-2016, macos-latest]
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: 8
      - run: sudo apt-get install -y nailgun
        if: runner.os == 'Linux'
      - run: brew install nailgun
        if: runner.os == 'macOS'
      - run: ./mill -i nativeTests

  test-linux-arm64-native-launcher:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: 8
      - uses: uraimo/run-on-arch-action@v2.0.10
        with:
          arch: aarch64
          distro: ubuntu20.04

          # Speeds up builds per the run-on-arch-action README
          githubToken: ${{ github.token }}

          setup: |
            mkdir -p output
            mkdir -p utils
            cp "$(cs get https://github.com/coursier/coursier/releases/download/v2.0.16/cs-aarch64-pc-linux)" utils/cs
            chmod +x utils/cs

          dockerRunArgs: |
            --volume "${PWD}/output:/output"
            --volume "${PWD}/utils:/utils"

          env: |
            JAVA_HOME: /jvm

          # The shell to run commands with in the container
          shell: /bin/bash

          # build-essential and libz-dev are required to build native images.
          # git is required by some of the launcher.sc logic.
          # python3-pip is required for some CLI tests.
          install: |
            apt-get update -q -y
            apt-get install -q -y build-essential libz-dev git python3-pip curl

          run: |
            set -e
            export PATH="/utils:$PATH"
            eval "$(cs java --env --jvm 11 --jvm-index https://github.com/coursier/jvm-index/raw/master/index.json)"
            ./mill -i nativeTests
